### 1. Стандартизировать данные.

In [2]:
import numpy as np
import pandas as pd
A = np.matrix([[1,2,3,4],
               [5,5,6,7],
               [1,4,2,3],
               [5,3,2,1],
               [8,1,2,2]])

df = pd.DataFrame(A,columns  = ['x1','x2','x3','x4'])
df_std  = (df - df.mean()) / (df.std())
df_std

x1        x2        x3        x4
0 -1.000000 -0.632456  0.000000  0.260623
1  0.333333  1.264911  1.732051  1.563740
2 -1.000000  0.632456 -0.577350 -0.173749
3  0.333333  0.000000 -0.577350 -1.042493
4  1.333333 -1.264911 -0.577350 -0.608121

### 2. Рассчитать ковариационную матрицу для объектов

In [3]:
cov_mat = np.cov(df_std.T)
cov_mat

array([[ 1.        , -0.31622777,  0.04811252, -0.18098843],
       [-0.31622777,  1.        ,  0.63900965,  0.61812254],
       [ 0.04811252,  0.63900965,  1.        ,  0.94044349],
       [-0.18098843,  0.61812254,  0.94044349,  1.        ]])

### 3. Рассчитать собственные значения и собственные векторы для ковариационной матрицы.

### 4. Отсортировать собственные значения и соответствующие им собственные векторы.

In [4]:
eigen_val, eigen_vectors = np.linalg.eig(cov_mat)
display(eigen_val)
display(eigen_vectors)

array([2.51579324, 1.0652885 , 0.39388704, 0.02503121])

array([[ 0.16195986, -0.91705888, -0.30707099,  0.19616173],
       [-0.52404813,  0.20692161, -0.81731886,  0.12061043],
       [-0.58589647, -0.3205394 ,  0.1882497 , -0.72009851],
       [-0.59654663, -0.11593512,  0.44973251,  0.65454704]])

### 5. Выбрать  наибольших собственных значений и сформировать матрицу соответствующих собственных векторов.

In [10]:
w=eigen_vectors[:,0:2]
display(w)

array([[ 0.16195986, -0.91705888],
       [-0.52404813,  0.20692161],
       [-0.58589647, -0.3205394 ],
       [-0.59654663, -0.11593512]])

### 6. Преобразовать исходные данные, умножив матрицу данных на матрицу отобранных собственных векторов.

In [12]:
df_std@w

0         1
0  0.014003  0.755975
1 -2.556534 -0.780432
2 -0.051480  1.253135
3  1.014150  0.000239
4  1.579861 -1.228917

>В параметр n_components в качестве значения можно передать количество необходимых компонентов или минимально допустимую объяснённую дисперсию в виде десятичной дроби. Например, если нам нужно столько компонент, чтобы они объясняли не менее 90 % разброса данных, то мы запишем n_components = 0.9.

## AUTO

In [14]:
#импортируем нужный алгоритм

from sklearn.decomposition import PCA
#определяем метод главных компонент с двумя компонентами
pca = PCA(n_components=2)
#обучаем алгоритм на наших данных
principalComponents = pca.fit_transform(df_std)
principalComponents

array([[-1.40033078e-02,  7.55974765e-01],
       [ 2.55653399e+00, -7.80431775e-01],
       [ 5.14801919e-02,  1.25313470e+00],
       [-1.01415002e+00,  2.38808310e-04],
       [-1.57986086e+00, -1.22891650e+00]])

### Задание 5.1
Найдите матрицу ковариаций для векторов $(3, 4, 1)$ и $(1, 6, 2)$. В качестве ответа укажите сумму всех значений матрицы, округлённую до двух знаков после точки-разделителя.

In [26]:
A = np.matrix([[3,1],
               [4,6],
               [1,2]])

df = pd.DataFrame(A.T,columns  = ['x1','x2','x3'])
df_std  = (df - df.mean()) / (df.std())
df_std

x1        x2        x3
0  0.707107 -0.707107 -0.707107
1 -0.707107  0.707107  0.707107

In [28]:
cov_mat = np.cov(df)
cov_mat.sum().round(2)

14.33

In [24]:
np.cov(np.array([3,4,1]),np.array([1,6,2])).sum()

14.333333333333332

### Задание 5.4
1 point possible (graded)
Дана матрица признаков:
```python
A = np.matrix([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])
```
Какое минимальное количество главных компонент надо выделить, чтобы сохранить информацию о как минимум 90 % разброса данных?

In [29]:
A = np.matrix([[8,7,2,9],
               [1,3,6,3],
               [7,2,0,3],
               [10,3,1,1],
               [8,1,3,4]])

df = pd.DataFrame(A,columns  = ['x1','x2','x3','x4'])
df_std  = (df - df.mean()) / (df.std())
df_std

#определяем метод главных компонент с двумя компонентами
pca = PCA(n_components=0.9)
#обучаем алгоритм на наших данных
principalComponents = pca.fit_transform(df_std)
principalComponents

array([[-1.61145254,  1.76368007,  0.01320928],
       [ 2.08441051,  1.01724955, -0.24417084],
       [-0.29568142, -0.95946326, -0.05272576],
       [-0.50390826, -1.24373821, -0.50808763],
       [ 0.3266317 , -0.57772816,  0.79177495]])