In [1]:
import numpy as np
import sympy
from sympy import diff, Symbol, solveset, Eq, symbols, exp

### Задание 3.1
Найдите экстремумы для функции $f(x) = -2x^3 -3x^2 + 12x - 4$. В качестве ответа запишите точку минимума:

In [2]:
x = Symbol('x')
f=-2*x**3-3*x**2+12*x-4
display(f)
temp=f.diff(x)
display(temp)
display(min(solveset(Eq(temp, 0), x)))

# temp=f.diff(x,2)
# display(temp)
# print(temp.subs(x,-2))
# print(temp.subs(x,1))
# display(solveset(Eq(temp, 0), x))

-2*x**3 - 3*x**2 + 12*x - 4

-6*x**2 - 6*x + 12

-2

$$f(x,y) = x^2 - 10x + y^2 -12y + 71$$

In [3]:
x, y = symbols('x y', real=True)
f=x**2-10*x+y**2-12*y+71
display(f)

print('Этап 1')
print('На первом этапе необходимо найти частные производные этой функции:')
f_x=f.diff(x)
f_y=f.diff(y)

display('f\'_x',f_x)
display('f\'_y',f_y)

print('Этап 2')
print('На втором этапе мы находим точки, в которых эти производные принимают нулевые значения:')
x_0=solveset(Eq(f_x, 0), x)
y_0=solveset(Eq(f_y, 0), y)
print('x_0=',x_0)
print('y_0=',y_0)

print('Этап 3')
print('Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.')
f_xx=f_x=f_x.diff(x)
f_xy=f_x=f_x.diff(y)
f_yx=f_x=f_y.diff(x)
f_yy=f_x=f_y.diff(y)

A=np.array([[f_xx,f_xy],[f_yx,f_yy]])
display(A)
A=np.array([[2,0],[0,2]])
print(A[0,0],'> 0')
# print('Определитель матрицы :\n',np.linalg.det(A))
print(np.linalg.det(A),"> 0")

x**2 - 10*x + y**2 - 12*y + 71

Этап 1
На первом этапе необходимо найти частные производные этой функции:


"f'_x"

2*x - 10

"f'_y"

2*y - 12

Этап 2
На втором этапе мы находим точки, в которых эти производные принимают нулевые значения:
x_0= {5}
y_0= {6}
Этап 3
Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.


array([[2, 0],
       [0, 2]], dtype=object)

2 > 0
4.0 > 0


### Задание 3.2
Найдите матрицу Гессе для функции $f(x,y) = e^x + 5y^3 x$:

In [4]:
x, y = symbols('x y', real=True)
f=exp(x)+5*y**3*x
display(f)

print('Этап 1')
print('На первом этапе необходимо найти частные производные этой функции:')
f_x=f.diff(x)
f_y=f.diff(y)

display('f\'_x',f_x)
display('f\'_y',f_y)

print('Этап 3')
print('Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.')
f_xx=f_x=f_x.diff(x)
f_xy=f_x=f_x.diff(y)
f_yx=f_x=f_y.diff(x)
f_yy=f_x=f_y.diff(y)

A=np.array([[f_xx,f_xy],[f_yx,f_yy]])
display(A)

5*x*y**3 + exp(x)

Этап 1
На первом этапе необходимо найти частные производные этой функции:


"f'_x"

5*y**3 + exp(x)

"f'_y"

15*x*y**2

Этап 3
Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.


array([[exp(x), 0],
       [15*y**2, 30*x*y]], dtype=object)

### Пример № 1

Исследовать на экстремумы функцию $f(x) = -x^2 + 6x - 2y^2 + 4y$.

In [7]:
x, y = symbols('x y', real=True)
f=-x**2+6*x-2*y**2+4*y
display(f)

print('Этап 1')
print('На первом этапе необходимо найти частные производные этой функции:')
f_x=f.diff(x)
f_y=f.diff(y)

display('f\'_x',f_x)
display('f\'_y',f_y)

print('Этап 2')
print('На втором этапе мы находим точки, в которых эти производные принимают нулевые значения:')
x_0=solveset(Eq(f_x, 0), x)
y_0=solveset(Eq(f_y, 0), y)
print('x_0=',x_0)
print('y_0=',y_0)

print('Этап 3')
print('Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.')
f_xx=f_x=f_x.diff(x)
f_xy=f_x=f_x.diff(y)
f_yx=f_x=f_y.diff(x)
f_yy=f_x=f_y.diff(y)

A=np.array([[f_xx,f_xy],[f_yx,f_yy]])
display(A)

A=np.float_(A)
temp=np.linalg.eig(A)[0]
print(temp)
print(temp[0],'< 0  значит функция идет в верх')
print(temp[1],'< 0  значит функция идет в верх')

-x**2 + 6*x - 2*y**2 + 4*y

Этап 1
На первом этапе необходимо найти частные производные этой функции:


"f'_x"

6 - 2*x

"f'_y"

4 - 4*y

Этап 2
На втором этапе мы находим точки, в которых эти производные принимают нулевые значения:
x_0= {3}
y_0= {1}
Этап 3
Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.


array([[-2, 0],
       [0, -4]], dtype=object)

[-2. -4.]
-2.0 < 0  значит функция идет в верх
-4.0 < 0  значит функция идет в верх


### Пример № 2

Найти экстремумы для функции $z = x^3 + 3xy^2 -15x - 12y + 1$.

In [33]:
x, y = symbols('x y', real=True)
f=x**3+3*x*y**2-15*x-12*y+1
display(f)

print('Этап 1')
print('На первом этапе необходимо найти частные производные этой функции:')
f_x=f.diff(x)
f_y=f.diff(y)

display('f\'_x',f_x)
display('f\'_y',f_y)

print('Этап 3')
print('Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.')
f_xx=f_x=f_x.diff(x)
f_xy=f_x=f_x.diff(y)
f_yx=f_x=f_y.diff(x)
f_yy=f_x=f_y.diff(y)

A=np.array([[f_xx,f_xy],[f_yx,f_yy]])
display(A)

print('Этап 2')
print('На втором этапе мы находим точки, в которых эти производные принимают нулевые значения:')
# x_0=solveset(Eq(f_x, 0), x)
# y_0=solveset(Eq(f_y, 0), y)
# display('x_0=',x_0)
# display('y_0=',y_0)

x**3 + 3*x*y**2 - 15*x - 12*y + 1

Этап 1
На первом этапе необходимо найти частные производные этой функции:


"f'_x"

3*x**2 + 3*y**2 - 15

"f'_y"

6*x*y - 12

Этап 3
Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.


array([[6*x, 0],
       [6*y, 6*x]], dtype=object)

Этап 2
На втором этапе мы находим точки, в которых эти производные принимают нулевые значения:


In [34]:
from sympy import *
 
# x, y = symbols('x, y')
eq1 = Eq(3*x**2+3*y**2-15,0)
eq2 = Eq(6*x*y-12, 0)
 
sol = solve([eq1, eq2], [x, y])
sol

[(-2, -1), (-1, -2), (1, 2), (2, 1)]

In [36]:
for i in sol:
    A=np.array([[f_xx.subs([(x,i[0]),(y,i[1])]),f_yx.subs([(x,i[0]),(y,i[1])])],[f_yx.subs([(x,i[0]),(y,i[1])]),f_yy.subs([(x,i[0]),(y,i[1])])]])
    # display(A)
    A=np.float_(A)
    print(i)
    A=np.float_(A)
    temp=np.linalg.eig(A)[0]
    print(temp)
    for q in temp:
        if q > 0 : print(q,'> 0  значит функция идет в низ')
        else:      print(q,'< 0  значит функция идет в верх')

(-2, -1)
[ -6. -18.]
-6.000000000000001 < 0  значит функция идет в верх
-18.0 < 0  значит функция идет в верх
(-1, -2)
[  6. -18.]
5.999999999999998 > 0  значит функция идет в низ
-18.000000000000004 < 0  значит функция идет в верх
(1, 2)
[18. -6.]
18.0 > 0  значит функция идет в низ
-6.0000000000000036 < 0  значит функция идет в верх
(2, 1)
[18.  6.]
18.0 > 0  значит функция идет в низ
5.999999999999998 > 0  значит функция идет в низ


### Задание 3.4
Найдите экстремумы функции $z = 4x^2 - 6xy -34x + 5y^2 + 42y + 7$.

In [9]:
x, y = symbols('x y', real=True)
f=4*x**2-6*x*y-34*x+5*y**2+42*y+7
display(f)

print('Этап 1')
print('На первом этапе необходимо найти частные производные этой функции:')
f_x=f.diff(x)
f_y=f.diff(y)

display('f\'_x',f_x)
display('f\'_y',f_y)

print('Этап 2')
# (2,-3)

eq1 = Eq(f_x,0)
eq2 = Eq(f_y, 0)
sol = solve([eq1, eq2], [x, y])
display(sol)

4*x**2 - 6*x*y - 34*x + 5*y**2 + 42*y + 7

Этап 1
На первом этапе необходимо найти частные производные этой функции:


"f'_x"

8*x - 6*y - 34

"f'_y"

-6*x + 10*y + 42

Этап 2


{x: 2, y: -3}

### Задание 3.5
Вычислите матрицу Гессе для функции $f(x,y) = x^3 - 2xy - y^6$ в точке $(1,2)$ и найдите её определитель:

In [15]:
x_0, y_0 = 1, 2
x, y = symbols('x y', real=True)
f=x**3-2*x*y-y**6
display(f)

print('Этап 1')
print('На первом этапе необходимо найти частные производные этой функции:')
f_x=f.diff(x)
f_y=f.diff(y)

display('f\'_x',f_x)
display('f\'_y',f_y)

print('Этап 3')
print('Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.')
f_xx=f_x=f_x.diff(x)
f_xy=f_x=f_x.diff(y)
f_yx=f_x=f_y.diff(x)
f_yy=f_x=f_y.diff(y)

A=np.array([[f_xx,f_xy],[f_yx,f_yy]])
display(A)
A=np.array([[f_xx.subs([(x,x_0),(y,y_0)]),f_yx.subs([(x,x_0),(y,y_0)])],[f_yx.subs([(x,x_0),(y,y_0)]),f_yy.subs([(x,x_0),(y,y_0)])]])
A=np.float_(A)
A
print('Определитель матрицы :\n',np.linalg.det(A).round())


x**3 - 2*x*y - y**6

Этап 1
На первом этапе необходимо найти частные производные этой функции:


"f'_x"

3*x**2 - 2*y

"f'_y"

-2*x - 6*y**5

Этап 3
Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.


array([[6*x, 0],
       [-2, -30*y**4]], dtype=object)

Определитель матрицы :
 -2884.0


### Задание 3.9
Найдите экстремумы функции $z = x^3 + y^3 - 3xy$.

In [26]:
x, y = symbols('x y', real=True)
f=x**3+y**3-3*x*y
display(f)

print('Этап 1')
# print('На первом этапе необходимо найти частные производные этой функции:')
f_x=f.diff(x)
f_y=f.diff(y)

display('f\'_x',f_x)
display('f\'_y',f_y)

print('Этап 2')
eq1 = Eq(f_x, 0)
eq2 = Eq(f_y, 0)
 
sol = solve([eq1, eq2], [x, y])
display(sol)

print('Этап 3')
# print('Наконец, переходим к третьему шагу — определению того, чем будет являться стационарная точка.')
f_xx=f_x=f_x.diff(x)
f_xy=f_x=f_x.diff(y)
f_yx=f_x=f_y.diff(x)
f_yy=f_x=f_y.diff(y)

A=np.array([[f_xx,f_xy],[f_yx,f_yy]])
display(A)
for i in sol:
    A=np.array([[f_xx.subs([(x,i[0]),(y,i[1])]),f_yx.subs([(x,i[0]),(y,i[1])])],[f_yx.subs([(x,i[0]),(y,i[1])]),f_yy.subs([(x,i[0]),(y,i[1])])]])
    A=np.float_(A)
    print(i)
    A=np.float_(A)
    temp=np.linalg.eig(A)[0]
    print(temp)
    for q in temp:
        if q > 0 : print(q,'> 0  значит функция идет в низ')
        else:      print(q,'< 0  значит функция идет в верх')
    

x**3 - 3*x*y + y**3

Этап 1


"f'_x"

3*x**2 - 3*y

"f'_y"

-3*x + 3*y**2

Этап 2


[(0, 0), (1, 1)]

Этап 3


array([[6*x, 0],
       [-3, 6*y]], dtype=object)

(0, 0)
[ 3. -3.]
2.9999999999999996 > 0  значит функция идет в низ
-3.000000000000001 < 0  значит функция идет в верх
(1, 1)
[9. 3.]
9.0 > 0  значит функция идет в низ
2.999999999999999 > 0  значит функция идет в низ
