## градиент

In [2]:
import numpy as np

Зададим массив, для которого хотим найти градиент, и вычислим его:

In [3]:
f = np.array([3, 7, 14, 23, 36, 47], dtype=float)
 
np.gradient(f)

# array([ 4. ,  5.5,  8. , 11. , 12. , 11. ])

array([ 4. ,  5.5,  8. , 11. , 12. , 11. ])

Если специально не определять аргумент varargs, то его значение равно 1, так что на границах вектора мы получаем обычную разность для соседних элементов массива:

In [4]:
print(f[1] - f[0], f[-1] - f[-2])

# (4.0, 11.0)

4.0 11.0


А вот внутри вектора для каждого элемента мы считаем разность его соседних значений, но уже поделённую на 2:

In [5]:
(f[2] - f[0])/2 # 5.5
(f[3] - f[1])/2 # 8.0
(f[4] - f[2])/2 # 11.0
(f[5] - f[3])/2 # 12.0

12.0

Шаг можно варьировать. При его изменении вычисления реализуются так же, но деление происходит на величину обычного шага у края и удвоенную величину шага для элементов внутри вектора:

In [7]:
print(np.gradient(f, 2))
# array([2.  , 2.75, 4.  , 5.5 , 6.  , 5.5 ])

for i in range(1, len(f) - 1):
    print((f[i + 1] - f[i - 1])/(2*2))
#2.75
#4.0
#5.5
#6.0

[2.   2.75 4.   5.5  6.   5.5 ]
2.75
4.0
5.5
6.0


### Задание 6.5
$$f(a,b) = (5 − a − 2b)^2$$
1. Вычислите $\overrightarrow{grad} f|_{M(1,1)}$:

In [26]:
import sympy
from sympy import *
m_a=1
m_b=1
a, b = symbols('a b')
f=(5-a-2*b)**2
f_a=f.diff(a)
print('f_a:',f_a)
f_b=f.diff(b)
print('f_b:',f_b)

print('f_a m:',f_a.subs({a:m_a, b:m_b}))
print('f_b m:',f_b.subs({a:m_a, b:m_b}))

f_a: 2*a + 4*b - 10
f_b: 4*a + 8*b - 20
f_a m: -4
f_b m: -8


### Решение
$$\frac{\partial f}{\partial a} = 2*a + 4*b - 10 \ \ \frac{\partial f}{\partial b} = 4a + 8b - 20$$
$$\nabla f = \left ( \frac{\partial f}{\partial a}, \frac{\partial f}{\partial b} \right ) = (2a + 4b - 10,\ 4a + 8b - 20)$$
$$\overrightarrow{grad} f = \left ( \frac{\partial f}{\partial a}, \frac{\partial f}{\partial b} \right ) = (2a + 4b - 10,\ 4a + 8b - 20)$$
$$\overrightarrow{grad} f|_M = (2a + 4b - 10,\ 4a + 8b - 20)|_{a=1,b=1} = (-4,-8)

2. Сколько решений имеет СЛАУ $\overrightarrow{grad} f = \overrightarrow{0}$?

In [31]:
solve([f_a, f_b],[a,b])

{a: 5 - 2*b}

a: 5 - 2*b означает что $a=5 - 2*b$ из этого вытекает если $b=0\ 5-2*0=5$ $\ a=5$ или $b=1\ 5-2*1=3$ $\ a=3$, а если $b=oo$ тогда  $f=5-2*oo$ 

значит ответов бесконечно много

3. В каких точках  $\overrightarrow{grad} f = \overrightarrow{0}$? Отметьте все подходящие варианты ответов:

In [34]:
q=np.array([[1,2],[1,3],[0,0],[5,0]])
for i in q:
    print(i,end='')
    print(i[0]==5-2*i[1])

[1 2]True
[1 3]False
[0 0]False
[5 0]True


### Задание 6.6
$L_2$-loss функция имеет вид $L = (2.1 − w_0 − w_1)^2 +(2.9 − w_0 − 3w_1)^2 +(4.1 − w_0 − 5w_1)^2$.
1. Сколько решений имеет СЛАУ $\overrightarrow{grad} L = \overrightarrow{0}$?
2. Вычислите точку, в которой $\overrightarrow{grad} L = \overrightarrow{0}$. Ответ округлите до двух знаков после точки-разделителя.

In [39]:
w_0, w_1 = symbols('w_0 w_1')
L=(2.1-w_0-w_1)**2+(2.9-w_0-3*w_1)**2+(4.1-w_0-5*w_1)**2
f_0=L.diff(w_0)
print('f_0:',f_0)
f_1=L.diff(w_1)
print('f_1:',f_1)

solve([f_0, f_1],[w_0,w_1])

f_0: 6.0*w_0 + 18.0*w_1 - 18.2
f_1: 18.0*w_0 + 70.0*w_1 - 62.6


{w_0: 1.53333333333333, w_1: 0.500000000000000}

Задание 6.7
Пусть дан одномерный массив f = np.array([8, 2, 8, 3, 5, 6, 5, 15]).

Вычислите градиент массива $f$, увеличив шаг сетки в семь раз, и укажите значение седьмого элемента массива получившихся градиентов $f$ (порядок элементов начинается с 0).

In [42]:
f = np.array([8, 2, 8, 3, 5, 6, 5, 15])
print(np.gradient(f, 7)[7])

1.4285714285714286
