In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn import tree

### Псевдокод такого алгоритма будет иметь вид (запускать его не нужно):

``` python
min_loss = inf
optimal_split_params = None
for j in range(M):
    thresholds = find_candidates_for_thresholds(X[:, j], y)
    for t in thresholds:
        split_params = (j, t)
        loss = calculate_loss(X, y, split_params)
        if loss < min_loss:
            min_loss = loss
            optimal_split_params = split_params
```

## Продалжаем здессь [DecisionTree_CART_3](DecisionTree_CART_3.ipynb)

In [2]:
data = pd.DataFrame({
    'age': [17, 64, 18, 20, 38, 49, 55, 25, 29, 31],
    'income': [25, 80, 22, 36, 37, 59, 74, 70, 33, 102],
    'loan': [1, 0, 1, 0, 1, 0, 0, 1, 1, 0]
})
x = data['age']
y = data['loan']

In [3]:
x = x.sort_values().drop_duplicates()
print(x.values)
# [17 18 20 25 29 31 38 49 55 64]

[17 18 20 25 29 31 38 49 55 64]


In [4]:
x_roll_mean = x.rolling(2).mean()
print(x_roll_mean.values)
# [ nan 17.5 19.  22.5 27.  30.  34.5 43.5 52.  59.5]

[ nan 17.5 19.  22.5 27.  30.  34.5 43.5 52.  59.5]


In [5]:
x_roll_mean = x_roll_mean.dropna()
print(x_roll_mean.values)
 
# [17.5 19.  22.5 27.  30.  34.5 43.5 52.  59.5]

[17.5 19.  22.5 27.  30.  34.5 43.5 52.  59.5]


In [6]:
y = y[x_roll_mean.index]
y_roll_mean = y.diff()
candidates = x_roll_mean[y_roll_mean != 0]
print(candidates.values)
# [17.5 19.  22.5 30.  34.5 43.5]

[17.5 19.  22.5 30.  34.5 43.5]


In [7]:
def find_candidates_for_thresholds(x, y):
    x = x.sort_values().drop_duplicates()
    x_roll_mean = x.rolling(2).mean().dropna()
    y = y[x_roll_mean.index]
    y_roll_mean = y.diff()
    candidates = x_roll_mean[y_roll_mean != 0]
    return candidates.values

In [8]:
print(find_candidates_for_thresholds(data['age'], data['loan']))
print(find_candidates_for_thresholds(data['income'], data['loan']))
# [17.5 19.  22.5 30.  34.5 43.5]
# [23.5 34.5 36.5 48.  64.5 72. ]

[17.5 19.  22.5 30.  34.5 43.5]
[23.5 34.5 36.5 48.  64.5 72. ]


### Задание 3.3

Дан датасет, состоящий из 15 наблюдений ($N=15$) и трёх факторов ($M=3$) — $x_1$, $x_2$, $x_3$. Решается задача регрессии. При этом целевая переменная $y$ и факторы полностью состоят из уникальных значений.

Сколько кандидатов в параметры разбиения решающего пня потребуется перебрать (полным перебором), чтобы найти оптимальные?

In [12]:
n=15
m=3
x=(n-1)*m
print(f'{x} = кандидатов в параметры разбиения решающего пня потребуется перебрать (полным перебором), чтобы найти оптимальные')

42 = кандидатов в параметры разбиения решающего пня потребуется перебрать (полным перебором), чтобы найти оптимальные


### Задание 3.4

Дана часть датасета о домах в штате Айова, состоящая из 15 наблюдений:
```python
ames_data = pd.read_csv('data/AmesHousing.csv')
ames_data = ames_data[(ames_data['Lot Frontage'] <=150) & (ames_data['Lot Area'] <=20000)]
ames_sample = ames_data[['Lot Frontage', 'Lot Area', 'SalePrice']].sample(
    n=15, #количество объектов
    random_state=42, #генератор случайных чисел
    ignore_index=True #сбрасываем счетчик индекса
)
```
Найдите уникальных кандидатов на пороговое значение $t$ для фактора $x_1$ (Lot Frontage)

In [13]:
ames_data = pd.read_csv('../../data/AmesHousing.csv')
ames_data = ames_data[(ames_data['Lot Frontage'] <=150) & (ames_data['Lot Area'] <=20000)]
ames_sample = ames_data[['Lot Frontage', 'Lot Area', 'SalePrice']].sample(
    n=15, #количество объектов
    random_state=42, #генератор случайных чисел
    ignore_index=True #сбрасываем счетчик индекса
)

In [16]:
print(find_candidates_for_thresholds(ames_sample['Lot Frontage'], ames_sample['SalePrice']))

[ 53.  58.  61.  65.  69.  71.  76.  86.  94. 101.]


### Задание 3.5
Для части датасета о домах в Айове из предыдущего задания найдите уникальных кандидатов на пороговое значение $t$ для фактора $x_2$ (Lot Area).

In [17]:
print(find_candidates_for_thresholds(ames_sample['Lot Area'], ames_sample['SalePrice']))

[ 5508.   7153.   7425.   7949.   8405.5  8526.5  8850.   9137.5  9466.
 10051.5 10507.  10834.  11365.  12288. ]
