In [1]:
# Загрузка библиотек
import numpy as np # для работы с массивами
import pandas as pd # для работы с DataFrame 
# from sklearn import datasets # для импорта данных
# import seaborn as sns # для визуализации статистических данных
# import matplotlib.pyplot as plt # для построения графиков


column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'PRICE']
boston_data = pd.read_csv('../../data/housing.csv', header=None, delimiter=r"\s+", names=column_names)
boston_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  PRICE  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [2]:
A = np.array([
    [1, 1, 1, 1],
    [1, 3, -2, 1],
    [1, 9, 4, 1]
]).T
y = np.array([4, 5, 2, 2])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat) 
# [2.4        0.46666667 0.13333333]

[2.4        0.46666667 0.13333333]


In [3]:
A = np.array([
    [1, 1, 1, 1, 1, 1, 1],
    [1, 3, -2, 1, 5, 13, 1],
    [3, 4, 5, -2, 4, 11, 3],
    [1, 9, 4, 1, 25, 169, 1],
    [3, 12, -10, -2, 20, 143, 3],
    [9, 16, 25, 4, 16, 121, 9]
    
]).T
y = np.array([4, 5, 2, 2, 6, 8, -1])
w_hat = np.linalg.inv(A.T@A)@A.T@y
print(w_hat)
## [-2.25799015  2.37672337 -0.1322068  -0.10208147 -0.26501791  0.29722471]

[-2.25799015  2.37672337 -0.1322068  -0.10208147 -0.26501791  0.29722471]


In [4]:
A = np.array([
    [1, 3, -2, 1, 5, 13, 1],
    [3, 4, 5, -2, 4, 11, 3],
    [4, 5, 2, 2, 6, 8, -1],
]).T
print(A)

[[ 1  3  4]
 [ 3  4  5]
 [-2  5  2]
 [ 1 -2  2]
 [ 5  4  6]
 [13 11  8]
 [ 1  3 -1]]


In [5]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=2, include_bias=True)

In [6]:
A_poly = poly.fit_transform(A)
display(pd.DataFrame(A_poly))

0     1     2    3      4      5      6      7     8     9
0  1.0   1.0   3.0  4.0    1.0    3.0    4.0    9.0  12.0  16.0
1  1.0   3.0   4.0  5.0    9.0   12.0   15.0   16.0  20.0  25.0
2  1.0  -2.0   5.0  2.0    4.0  -10.0   -4.0   25.0  10.0   4.0
3  1.0   1.0  -2.0  2.0    1.0   -2.0    2.0    4.0  -4.0   4.0
4  1.0   5.0   4.0  6.0   25.0   20.0   30.0   16.0  24.0  36.0
5  1.0  13.0  11.0  8.0  169.0  143.0  104.0  121.0  88.0  64.0
6  1.0   1.0   3.0 -1.0    1.0    3.0   -1.0    9.0  -3.0   1.0

In [7]:
def polynomial_regression(X, y, k):
    poly = PolynomialFeatures(degree=k, include_bias=True)
    X_poly = poly.fit_transform(X)
    w_hat = np.linalg.inv(X_poly.T@X_poly)@X_poly.T@y
    y_pred = X_poly @ w_hat
    return X_poly, y_pred, w_hat

In [8]:
A = boston_data[['LSTAT', 'PTRATIO', 'RM', 'CRIM']]
y = boston_data[['PRICE']]
 
A_poly, y_pred, w_hat = polynomial_regression(A, y, 1)
A_poly2, y_pred2, w_hat2 = polynomial_regression(A, y, 2)
A_poly3, y_pred3, w_hat3 = polynomial_regression(A, y, 3)
A_poly4, y_pred4, w_hat4 = polynomial_regression(A, y, 4)
A_poly5, y_pred5, w_hat5 = polynomial_regression(A, y, 5)

In [9]:
from sklearn.metrics import mean_absolute_percentage_error
 
print('MAPE для полинома 1-й степени {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred)*100))
print('MAPE для полинома 2-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred2)*100))
print('MAPE для полинома 3-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred3)*100))
print('MAPE для полинома 4-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred4)*100))
print('MAPE для полинома 5-й степени  {:.2f}%'.format(mean_absolute_percentage_error(y, y_pred5)*100))
## MAPE для полинома 1-й степени 18.20%
## MAPE для полинома 2-й степени 13.41%
## MAPE для полинома 3-й степени 12.93%
## MAPE для полинома 4-й степени 10.74%
## MAPE для полинома 5-й степени 70.18%

MAPE для полинома 1-й степени 18.20%
MAPE для полинома 2-й степени  13.41%
MAPE для полинома 3-й степени  12.93%
MAPE для полинома 4-й степени  10.77%
MAPE для полинома 5-й степени  662.68%


In [10]:
display(pd.DataFrame(w_hat5).describe())

PRICE
count     126.000000
mean      805.820580
std     22191.726671
min   -109333.207771
25%        -0.677433
50%        -0.000720
75%         0.964111
max    220184.122046

In [11]:
# считаем матрицу корреляций (без столбца из единиц)
C = pd.DataFrame(A_poly5[:, 1:]).corr()
# считаем ранг корреляционной матрицы
print('Ранг корреляционной матрицы:', np.linalg.matrix_rank(C))
# считаем количество факторов (не включая столбец из единиц)
print('Количество факторов:', A_poly5[:, 1:].shape[1])
# Ранг корреляционной матрицы: 110
# Количество факторов: 125

Ранг корреляционной матрицы: 110
Количество факторов: 125


In [12]:
# считаем матрицу корреляций (без столбца из единиц)
C = pd.DataFrame(A_poly4[:, 1:]).corr()
# считаем ранг корреляционной матрицы
print('Ранг корреляционной матрицы:', np.linalg.matrix_rank(C))
# считаем количество факторов (не включая столбец из единиц)
print('Количество факторов:', A_poly4[:, 1:].shape[1])
## Ранг корреляционной матрицы: 69
## Количество факторов: 69

Ранг корреляционной матрицы: 69
Количество факторов: 69


In [13]:
display(pd.DataFrame(w_hat4).describe())

PRICE
count    70.000000
mean    -50.946155
std     887.871883
min   -6929.950470
25%      -0.187947
50%      -0.000786
75%       0.322228
max    2305.386189

In [14]:
# подключаем библиотеку
from sklearn import linear_model

def polynomial_regression_sk(X, y, k):
    poly = PolynomialFeatures(degree=k, include_bias=False)
    X_poly = poly.fit_transform(X)
    lr = linear_model.LinearRegression().fit(X_poly, y)
    y_pred = lr.predict(X_poly)
    return X_poly, y_pred, lr.coef_

A = boston_data[['LSTAT', 'PTRATIO', 'RM', 'CRIM']]
y = boston_data[['PRICE']]

for k in range(1, 6):
    A_poly, y_pred, w_hat = polynomial_regression_sk(A, y, k)
    print(
        "MAPE для полинома степени {} — {:.2f}%, СКО — {:.0f}".format(
            k, mean_absolute_percentage_error(y, y_pred)*100, w_hat.std()
        )

    )
## MAPE для полинома степени 1 — 18.20%, СКО — 2
## MAPE для полинома степени 2 — 13.41%, СКО — 5
## MAPE для полинома степени 3 — 12.93%, СКО — 9
## MAPE для полинома степени 4 — 10.74%, СКО — 304
## MAPE для полинома степени 5 — 9.02%, СКО — 17055

MAPE для полинома степени 1 — 18.20%, СКО — 2
MAPE для полинома степени 2 — 13.41%, СКО — 5
MAPE для полинома степени 3 — 12.93%, СКО — 9
MAPE для полинома степени 4 — 10.74%, СКО — 304
MAPE для полинома степени 5 — 9.02%, СКО — 17055


### Задание 6.1

Построена модель полиномиальной регрессии следующего вида:
$$ y=10.4+8 \cdot x_1+0.5 \cdot x_2+3 \cdot x_{1}^{2}+0.4 \cdot x_{2}^{2}+0 \cdot x_1 x_2 $$

Поступило новое наблюдение, которое характеризуется вектором .
$$ x_{new}=(x_{1new}, x_{2new})^T=(1, 4)^T $$

Сделайте прогноз целевой переменной с помощью полученной полиномиальной регрессии. Ответ округлите до первого знака после точки-разделителя.

In [30]:
x=np.array([1, 4])
w=np.array([10.4, 8, 0.5, 3, 0.4, 0])
y=10.4+8*x[0]+0.5*x[1]+3*x[0]**2+0.4*x[1]**2+0*x[0]*x[1]
print(round(y,1))
y=w[0]+w[1]*x[0]+w[2]*x[1]+w[3]*x[0]**2+w[4]*x[1]**2+w[5]*x[0]*x[1]
print(round(y,1))

29.8
29.8


### Задание 6.2
Строится полиномиальная регрессия второй степени от одного фактора . Как будет выглядеть матрица наблюдений , если:
$$\vec{x}=\left(\begin{array}{c}
1 \\3 \\-2 \\9
\end{array}\right)$$

В качестве ответа введите элементы полученной матрицы A.

Заполняйте поля слева направо, сверху вниз.

In [33]:
x=np.array([[1],[ 3], [-2],[ 9]])
k=2 # полиномиальная регрессия второй степени
poly = PolynomialFeatures(degree=k, include_bias=True)
A = poly.fit_transform(x)
display(pd.DataFrame(A))

0    1     2
0  1.0  1.0   1.0
1  1.0  3.0   9.0
2  1.0 -2.0   4.0
3  1.0  9.0  81.0

### Задание 6.3
Какую размерность будет иметь матрица измерений A, если в наборе данных пять факторов, а в качестве модели используется полином второй степени?

$$ c = \frac{n!}{(n-d)!d!} $$
$$ n = k + d $$
где  $k$— количество факторов,  $d$— степень полинома, а  $!$— символ факториала.

In [49]:
k=5
d=2

def fact(x):
    fact = 1
    for i in range(1, x+1):
        fact = fact * i
    return fact

n=k+d
c= fact(n)/(fact(n-d)*fact(d))

print(c)

21.0


### Задание 6.4
С помощью классического МНК найдите коэффициенты полиномиальной регрессии, если используется полином второй степени и задан фактор X и y целевая переменная .
$$ \vec{y} = w_0 + w_1 \vec{x} + w_2 \vec{x}^2 $$
$$ \vec{x}=\left(\begin{array}{c}
1 \\3 \\-2 \\9
\end{array}\right) \vec{y}=\left(\begin{array}{c}
3 \\7 \\-5 \\21
\end{array}\right) $$

В качестве ответа приведите координаты вектора коэффициентов $w_0$, $w_1$, $w_2$, округлив их до первого знака после точки-разделителя.

In [37]:
y=np.array([[3],[7], [-5],[21]])

x_temp, y_temp, w_temp = polynomial_regression(x, y, k)

display(x_temp)
print(w_temp.round(1))



array([[ 1.,  1.,  1.],
       [ 1.,  3.,  9.],
       [ 1., -2.,  4.],
       [ 1.,  9., 81.]])

[[ 0.1]
 [ 2.5]
 [-0. ]]
