In [2]:
import numpy as np

### Задание 1.1
Найдите скалярное произведение векторов:

In [3]:
v1=np.array([-1,2,-7,9])
v2=np.array([2,8,2,-1])
print('v1\n',v1,'\nV2\n',v2)
print('скалярное произведение векторов:',v1@v2)
# v1@v2=-1*2+2*8+(-7)*2+9*(-1)=-2+16-14-9=-9

v1
 [-1  2 -7  9] 
V2
 [ 2  8  2 -1]
скалярное произведение векторов: -9


### Задание 1.4
Задана матрица

Найдите матрицу Грама A.T*A.

In [4]:
A=np.array([[1,1],[1,2]])
print('A\n',A)
print('матрицу Грама:\n',A.T@A)

A
 [[1 1]
 [1 2]]
матрицу Грама:
 [[2 3]
 [3 5]]


In [5]:
A=np.array([[1,1],[0,0]])
print('A\n',A)
print(np.linalg.det(A))
print('rk(A):\n',np.linalg.matrix_rank(A))


A
 [[1 1]
 [0 0]]
0.0
rk(A):
 1


### Задание 1.6
Вычислите обратную матрицу , если:

In [6]:
A=np.array([[1,2],[3,7]])
print('A\n',A)
print(np.linalg.det(A))
print('rk(A):\n',np.linalg.matrix_rank(A))
print('A inversed:\n',np.linalg.inv(A))
A@np.linalg.inv(A)

A
 [[1 2]
 [3 7]]
0.9999999999999991
rk(A):
 2
A inversed:
 [[ 7. -2.]
 [-3.  1.]]


array([[ 1.00000000e+00,  0.00000000e+00],
       [-3.55271368e-15,  1.00000000e+00]])

### Задание 1.7
Найдите ранг матрицы системы, составленной из векторов:

In [7]:
v1=np.array([2,10,-2])
v2=np.array([3,2,-2])
v3=np.array([8,14,-6])
A=np.array([v1, v2, v3])
print('A\n',A)
print('rk(A):\n',np.linalg.matrix_rank(A))


A
 [[ 2 10 -2]
 [ 3  2 -2]
 [ 8 14 -6]]
rk(A):
 2


### Задание 1.8

Определите линейную (не)зависимость системы векторов:


Получили ступенчатую матрицу. Ранг матрицы (количество ступенек) равно rk(A)=2.

Ранг не равен количеству исходных векторов, а значит все векторы являются линейно зависимыми

https://www.dmitrymakarov.ru/python/jupyter-notebook-14-02/

$e^{i\pi} + 1 = 0$

\begin{equation}
e^x=\sum_{i=0}^\infty \frac{1}{i!}x^i
\end{equation}

$$ \hat{y} = \theta_0 + \theta_1 x_1 + \theta_2 x_2 + \ \ ... \ \ + \\ \theta_n x_n $$

$$
\left(\frac{1}{2}\right) \qquad (\frac{1}{2})
$$

$$
\big( \Big( \bigg( \Bigg( \\
\big] \Big] \bigg] \Bigg] \\
\big\{ \Big\{ \bigg\{ \Bigg\{
$$

$$
\left\{
    \begin{matrix}
    4x  + 3y = 20 \\
    -5x + 9y = 26
    \end{matrix}
\right.
$$

$$ (A \mid \vec{b})=\left(\begin{array}{cc|c} 1 & 1 & 1 \\ 1 & 2 & 2 \\ 1 & 1 & 12 \end{array}\right) $$

### Задание 1.9

Сколько нетривиальных решений имеет представленная ниже система уравнений?

$$
\left\{
    \begin{matrix}
    10w_1  + 2w_2 = 0 \\
    5w_1 + w_2 = 0
    \end{matrix}
\right.
$$

In [8]:
A=np.array([[5,10],[1,2]])
print('A\n',A)
print('rk(A):\n',np.linalg.matrix_rank(A))

A
 [[ 5 10]
 [ 1  2]]
rk(A):
 1


Перед нами однородная СЛАУ. Такие СЛАУ имеют только два случая решений:

* Бесконечное множество решений, если уравнения являются пропорциональными другу, то есть ранг матрицы системы  меньше количества A неизвестных.
* Не имеет решений, если уравнения не являются пропорциональными, то есть ранг матрицы системы A равен количеству неизвестных.

Видно, что уравнения в нашей системе пропорциональны друг другу: если умножить первое на 2, получится второе уравнение, а значит одно из них можно убрать. Тогда останется только одно уравнение на две неизвестных:
$$ 5w_1 + w_2 = 0 $$
Таким образом, количество неизвестных (2) больше, чем количество линейно независимых уравнений, или ранг матрицы (1), а значит система имеет бесконечное множество решений

### Задание 1.10
Запишите СЛАУ в матричном виде и классифицируйте её:

$$
\left\{
    \begin{matrix}
    5w_1  + w_2 + 3w_1 = 1 \\
    2w_2 + 8w_3 = 10 \\
    10w_1 + 2w_3 = 0
    \end{matrix}
\right.
$$

$$
\left\{
    \begin{matrix}
    5w_1  + w_2 + 3w_1 = 1 \\
    0.2w_2 + 0.8w_3 = 1 \\
    10w_1 + 2w_3 = 0
    \end{matrix}
\right.
$$

In [9]:
A=np.array([[4,7,-1],[-4,2,5],[0,9,4]])
B=np.array([[4,7,-1,7],[-4,2,5,3],[0,9,4,10]])
print('rk(A):\n',np.linalg.matrix_rank(A))
print('rk(B):\n',np.linalg.matrix_rank(B))
B

rk(A):
 2
rk(B):
 2


array([[ 4,  7, -1,  7],
       [-4,  2,  5,  3],
       [ 0,  9,  4, 10]])

$
\left\{
    \begin{matrix}
    w_1 + w_2 = 1 \\
    w_1 + 2w_2 = 2 \\
    w_1 + w_2 = 12
    \end{matrix}
\right.
$ =>
$ (A \mid \vec{b})=\left (\begin{array}{cc|c} 1 & 1 & 1 \\ 1 & 2 & 2 \\ 1 & 1 & 12 \end{array}\right) $

$ A =\left(\begin{array}{cc} 1 & 1 \\ 1 & 2\\ 1 & 1 \end{array}\right) $

$ \vec{b} = ( 1 , 2 , 12 )^T $

$$ e = b - \hat{b} $$

$$ G = A.T * A  =>
G = \left(\begin{array}{ccc} 1 & 1 & 1 \\ 1 & 2 & 1 \end{array}\right) 
* \left(\begin{array}{cc} 1 & 1 \\ 1 & 2\\ 1 & 1 \end{array}\right)
= \left(\begin{array}{cc} 3 & 4 \\ 4 & 6 \end{array}\right) $$

Находим определитель матрицы $ (A^{T}A) $
'Определитель матрицы Грама'
$$ det(A^T A) = 3 \cdot 6 - 4 \cdot 4 = 2 $$
$ x=2 $ будет в знаменателе

Находим обратную матрицу $(A^{T}A)^{-1}$

$$ (A^{T}A)^{-1} = \left(\begin{array}{cc} 3 & 4 \\ 4 & 6 \end{array}\right) ^{-1} 
= \frac{1}{x = 2} * \left(\begin{array}{cc} 6 & -4 \\ -4 & 3 \end{array}\right) 
= \left(\begin{array}{cc} 3 & -2 \\ -2 & 1.5 \end{array}\right) $$
$$ (A^{T}A)^{-1} = \left(\begin{array}{cc} 3 & 4 \\ 4 & 6 \end{array}\right) ^{-1} 
= \frac{1}{2} * \left(\begin{array}{cc} 6 & -4 \\ -4 & 3 \end{array}\right) 
= \left(\begin{array}{cc} 3 & -2 \\ -2 & 1.5 \end{array}\right) $$

$$ A * \vec{b} = \left(\begin{array}{ccc} 1 & 1 & 1 \\ 1 & 2 & 1 \end{array}\right)
 *  \left(\begin{array}{c} 1 \\ 2\\ 12 \end{array}\right) 
 = \left(\begin{array}{c} 15 \\ 17 \end{array}\right)$$

$$ \left(\begin{array}{c} \hat{w} \\ \hat{w} \end{array}\right)
= \left(\begin{array}{cc} 3 & -2 \\ -2 & 1.5 \end{array}\right) 
* \left(\begin{array}{c} 15 \\ 17 \end{array}\right)
= \left(\begin{array}{c} 11 \\ -4.5 \end{array}\right)$$

$$ \hat{b} = \hat{w_1} * A_1 + \hat{w_2} * A_2
= 11 * \left(\begin{array}{c} 1 \\ 1 \\ 1 \end{array}\right) 
-4.5 * \left(\begin{array}{c} 1 \\ 2 \\ 1 \end{array}\right) 
= \left(\begin{array}{c} 6.5 \\ 2 \\ 6.5 \end{array}\right)$$

$$ e = b - \hat{b} = \left(\begin{array}{c} 1 \\ 2 \\ 12 \end{array}\right)
- \left(\begin{array}{c} 6.5 \\ 2 \\ 6.5 \end{array}\right)
= \left(\begin{array}{c} -5.5 \\ 0 \\ 5.5 \end{array}\right)$$

Убедимся, что данный вектор действительно ортогонален столбцам матрицы А. Для этого найдём их скалярные произведения:
$$ (e,A_1)= e^T*A_1= (-5.5, 0, 5.5) * \left(\begin{array}{c} 1 \\ 1 \\ 1 \end{array}\right) = 0 $$
$$ (e,A_2)= e^T*A_2= (-5.5, 0, 5.5) * \left(\begin{array}{c} 1 \\ 2 \\ 1 \end{array}\right) = 0 $$

In [10]:
A=np.array([[1,1],[1,2],[1,1]])
At=A.T
b=np.array([1,2,12])
print("A\n",A)
print("\nA.T\n",At)
B=(At@A)
print("\nA.T*A\n",B)
print('Определитель матрицы Грама:\n',np.linalg.det(B))

B_inv=np.linalg.inv(B).round(3)
# B_inv=np.array([[13.5,1],[1,3]])
print('\nB inversed:\n',B_inv)
q=At@b
print("\nA.T*b\n",q)
w=B_inv@q
print("\nB_inv*q\n",w)
r=At[0]*w[0]+At[1]*w[1]
print(r)
e=b-r
print('e',e)

A
 [[1 1]
 [1 2]
 [1 1]]

A.T
 [[1 1 1]
 [1 2 1]]

A.T*A
 [[3 4]
 [4 6]]
Определитель матрицы Грама:
 2.0

B inversed:
 [[ 3.  -2. ]
 [-2.   1.5]]

A.T*b
 [15 17]

B_inv*q
 [11.  -4.5]
[6.5 2.  6.5]
e [-5.5  0.   5.5]


### Задание 2.9
Вычислите вектор ошибок  для приближённого решения системы уравнений:

$$ \left(\begin{array}{c} \hat{w} \\ \hat{w} \end{array}\right)
= \left(\begin{array}{c} 1 \\ 1 \end{array}\right) 
\left\{
    \begin{matrix}
    w_1 - 5w_2 = 1 \\
    2w_1 + w_2 = 2 \\
    w_1 + w_2 = 2
    \end{matrix}
\right.$$

$ A =\left(\begin{array}{cc} 1 & -5 \\ 2 & 1 \\ 1 & 1 \end{array}\right) $

$ \vec{b} = ( 1 , 2 , 2 )^T $

$ \hat{w_1} = (1, 1)$

$ \hat{b} = \hat{w_1} * A_1 + \hat{w_2} * A_2 $

$$ e= \vec{b} - A * \hat{w} => \left(\begin{array}{c} 1 \\ 2 \\ 2 \end{array}\right) 
- \left(\begin{array}{cc} 1 & -5 \\ 2 & 1 \\ 1 & 1 \end{array}\right)
 * \left(\begin{array}{c} 1 \\ 1 \end{array}\right) 
 = \left(\begin{array}{c} 1 \\ 2 \\ 2 \end{array}\right) 
 - \left(\begin{array}{c} -4 \\ 3 \\ 2 \end{array}\right)
 = \left(\begin{array}{c} 5 \\ -1 \\ 0 \end{array}\right)$$

In [11]:
A=np.array([[1,-5],[2,1],[1,1]])
b=np.array([1,2,2])
w=np.array([1,1])
b-A@w

array([ 5, -1,  0])

### Задание 2.11
Найдите $ OLS $ -оценку для коэффициентов $w_1$, $w_2$ СЛАУ:
$$ \left\{
    \begin{matrix}
    w_1 + 2w_2 = 1 \\
    -3w_1 + w_2 = 4 \\
    w_1 + 2w_2 = 5 \\
    w_1 + w_2 = 0
    \end{matrix}
\right.$$


$ A =\left(\begin{array}{cc} 1 & 2 \\ -3 & 1 \\ 1 & 2 \\ 1 & -1 \end{array}\right) $ 

$ \vec{b} = ( 1 , 4 , 5 , 0)^T $

$$ G=A^T*A $$

In [12]:
A=np.array([[1,2],[-3,1],[1,2],[1,-1]])
b=np.array([1,4,5,0])
At=A.T
G=At@A
print(G)

[[12  0]
 [ 0 10]]


$$ G^{ -1}$$

In [13]:
G_inv=np.linalg.inv(G)
G_inv

array([[0.08333333, 0.        ],
       [0.        , 0.1       ]])

$$ A^{T} \vec{b} $$

In [14]:
q=At@b
q

array([-6, 16])

$$ \vec{w}= G^{-1}*(A^{T} \vec{b})$$

In [15]:
G_inv@q

array([-0.5,  1.6])

$$ \left\{
    \begin{matrix}
    16w_1 - 4w_2 = 5 \\
    3w_1 - w_2 = 2 \\
    \end{matrix}
\right.$$

In [18]:
A=np.array([[16,-4],[3,-1]])
b=np.array([5,2])
At=A.T
print("A\n",A)
print("\nA.T\n",At)
B=(At@A)
print("\nA.T*A\n",B)
print('Определитель матрицы Грама:\n',np.linalg.det(B))
B_inv=np.linalg.inv(B)
print('\nB inversed:\n',B_inv)
q=At@b
print("\nA.T*b\n",q)
w=B_inv@q
print("\nB_inv*q\n",w)
r=At[0]*w[0]+At[1]*w[1]
print(r)
e=b-r
print('e',e)

A
 [[16 -4]
 [ 3 -1]]

A.T
 [[16  3]
 [-4 -1]]

A.T*A
 [[265 -67]
 [-67  17]]
Определитель матрицы Грама:
 15.999999999999991

B inversed:
 [[ 1.0625  4.1875]
 [ 4.1875 16.5625]]

A.T*b
 [ 86 -22]

B_inv*q
 [-0.75 -4.25]
[5. 2.]
e [0. 0.]
