In [1]:
import numpy as np

In [2]:
s = np.array([33, 65, 50, 45])
s
## array([33, 65, 50, 45])

array([33, 65, 50, 45])

In [3]:
s[2]
## 50

50

In [4]:
len(s) # dim(s)
## 4

4

# + -

In [5]:
a = np.array([10, 8, 5, 1])
b = np.array([5, 15, 9, 7])
print(a + b)
## array([15, 23, 14,  8])
print(a - b)
## array([ 5, -7, -4, -6])

[15 23 14  8]
[ 5 -7 -4 -6]


# *

In [6]:
a = np.array([120, 45, 68])
omega = 0.2
c = a * omega
c
## array([24. ,  9. , 13.6])

array([24. ,  9. , 13.6])

### Деление

In [54]:
A=np.random.randint(-4, 4, (4,4))
display(A)
B=np.linalg.inv(A)
display(B)
(B@A).round()

array([[ 2,  2, -1, -1],
       [ 3, -3, -2, -3],
       [ 3, -4,  2,  0],
       [-3,  3,  0,  1]])

array([[ 0.2 , -0.3 , -0.2 , -0.7 ],
       [ 0.3 ,  0.05,  0.2 ,  0.45],
       [ 0.3 ,  0.55,  1.2 ,  1.95],
       [-0.3 , -1.05, -1.2 , -2.45]])

array([[ 1., -0., -0., -0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1., -0.],
       [ 0.,  0., -0.,  1.]])

# ЛИНЕЙНАЯ КОМБИНАЦИЯ ВЕКТОРОВ

In [7]:
p = np.array([2, 4, 5])
v = np.array([8, 10, 2])
s = np.array([0, 12, 7])
omega1 = 500
omega2 = 100
omega3 = 0
u = omega1*p + omega2*v + omega3*s
u
## array([1800, 3000, 2700])

array([1800, 3000, 2700])

# Скалярное произведение векторов
В Python скалярное произведение векторов вычисляется при помощи функции np.dot()

In [8]:
a = np.array([65, 70, 120, 30])
w = np.array([0.4, 0.4, 0.2, 0.8])
np.dot(a, w)
## 102.0

102.0

# задачи

1. Аренда
2. Площадь
3. Комнаты
4. Этаж
5. Демонстрационные две недели
6. Жилая площадь

In [9]:
import pandas as pd
Hut_Paradise_DF = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})
arr_Hut_Paradise_DF=Hut_Paradise_DF.values
display(Hut_Paradise_DF)
arr_Hut_Paradise_DF

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

array([[ 65,  50,   3,   5,   8,  37],
       [ 70,  52,   2,  12,   4,  40],
       [120,  80,   1,  10,   5,  65],
       [ 35,  33,   1,   3,  10,  20],
       [ 40,  33,   1,   6,  20,  16],
       [ 50,  44,   2,  13,  12,  35],
       [100,  80,   4,   8,   5,  60],
       [ 90,  65,   3,  21,   1,  50],
       [ 85,  65,   2,   5,  10,  40]], dtype=int64)

### Задание 3.3

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

In [10]:
# длина вектора
# l=np.linalg.norm(arr_Hut_Paradise_DF[4])
print('вектор параметров квартиры номер 5 \n',arr_Hut_Paradise_DF[4])

вектор параметров квартиры номер 5 
 [40 33  1  6 20 16]


### Задание 3.4
Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:

In [11]:
print('вектор этажей всех квартир \n',arr_Hut_Paradise_DF[:,3])

вектор этажей всех квартир 
 [ 5 12 10  3  6 13  8 21  5]


### Задание 3.5
Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [12]:
print('вектор нежилой площади \n',arr_Hut_Paradise_DF[:,1]-arr_Hut_Paradise_DF[:,5])

вектор нежилой площади 
 [13 12 15 13 17  9 20 15 25]


### Задание 3.6
Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [13]:
time = np.array([10,20,30,15,5,40,20,8,20])
print('продолжительность просмотров в минутах во всех квартирах за две недели = ', arr_Hut_Paradise_DF[:,4]@time)
# np.dot(arr_Hut_Paradise_DF[:,4],time)

продолжительность просмотров в минутах во всех квартирах за две недели =  1348


### Задание 3.7
Составьте линейную комбинацию векторов V и W с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [14]:
u=np.array([3,0,1,1,1])
v=np.array([0,1,0,2,-2])
w=np.array([1,-4,-1,0,-2])
omega_v=2
omega_w=-3

x=v*omega_v+w*omega_w
print('линейная комбинация векторов V и W \n',x)

линейная комбинация векторов V и W 
 [-3 14  3  4  2]


### Задание 3.8
Будет ли эта комбинация ортогональна вектору ?

In [15]:
#пропорциональность и ортогональность
print("(u,x):",np.dot(u,x))

(u,x): 0


if c @ u == 0:
    print('Ортогональны')
else:
    print('Не ортогональны')

In [16]:
A = np.array([
    [1, -5, 3], 
    [2, 2, 1],
    [0, 3, 1],
    [2, 4, 12]
])

In [17]:
print(A.shape)
## (4, 3)
print('a_23=', A[1, 2], 'a_32=', A[2, 1], 'a_33=', A[2,2])
## a_23= 1 a_32= 3 a_33= 1

(4, 3)
a_23= 1 a_32= 3 a_33= 1


In [18]:
Husband_Income = np.array([100,220,140])             # Доход мужа
Wife_Income = np.array([150,200,130])                # Доход жены
Mother_In_Law_Income = np.array([90,80,100])         # Доход тёщи

Husband_Consumption = np.array([50,50,60])           # Потребление мужа
Wife_Consumption = np.array([100,80,140])            # Потребление жены
Mother_In_Law_Consumption = np.array([100,20,140])   # Потребление тёщи

In [19]:
A = np.zeros((5,5),int)
A.flat[0::6] = -2
A.flat[1::6] = 1
A.flat[5::6] = 1
A

# array([[-2,  1,  0,  0,  0],
#        [ 1, -2,  1,  0,  0],
#        [ 0,  1, -2,  1,  0],
#        [ 0,  0,  1, -2,  1],
#        [ 0,  0,  0,  1, -2]])

array([[-2,  1,  0,  0,  0],
       [ 1, -2,  1,  0,  0],
       [ 0,  1, -2,  1,  0],
       [ 0,  0,  1, -2,  1],
       [ 0,  0,  0,  1, -2]])

### Задание 5.1
Составьте матрицу  Inc доходов семьи, расположив доходы мужа, жены и тёщи в первый, второй и третий столбцы матрицы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [20]:
Inc=np.array([Husband_Income,Wife_Income,Mother_In_Law_Income])
Inc=Inc.T
n=Inc.shape
n=min(n)
a=np.zeros(n)
for i in range(n):
    a[i]=Inc[i,i]
print('диагональные элементы',a)

диагональные элементы [100. 200. 100.]


### Задание 5.2
Составьте матрицу Cons расходов семьи, расположив расходы мужа, жены и тёщи в первый, второй и третий столбцы.

В качестве ответ запишите диагональные элементы (по главной диагонали) этой матрицы через запятую, без пробелов. Пример ввода ответа: 1,1,1.

In [21]:
Cons=np.array([Husband_Consumption, Wife_Consumption, Mother_In_Law_Consumption])
Cons=Cons.T
n=Cons.shape
n=min(n)
a=np.zeros(n)
for i in range(n):
    a[i]=Cons[i,i]
print('диагональные элементы',a)

диагональные элементы [ 50.  80. 140.]


### Задание 5.3

Доходы представлены до уплаты налогов. Налоговая ставка — 13 %. Вычислите матрицу доходов семьи Ивановых после уплаты налогов.

Используйте полученную Inc ранее матрицу , где доходы расположены по столбцам.

Выберите список элементов из первой строки этой матрицы (строки нумеруются с 1):

In [22]:
temp=Inc*0.87 # Inc-Inc*0.13
print('список элементов из первой строки этой матрицы\n',temp[0])


список элементов из первой строки этой матрицы
 [ 87.  130.5  78.3]


### Задание 5.4

Вычислите матрицу P, которая покажет баланс семьи Ивановых за один месяц (то есть разницу между доходами после вычета налога и расходами).

Выберите список элементов из третьей строки этой матрицы:

In [23]:
P=temp-Cons
# array([[ 37. ,  30.5, -21.7],
#        [141.4,  94. ,  49.6],
#        [ 61.8, -26.9, -53. ]])

print('список элементов из третьей строки этой матрицы',P[2])

список элементов из третьей строки этой матрицы [ 61.8 -26.9 -53. ]


In [24]:
A = np.matrix("1, -5; 2, 2; 0, 3")
B = np.matrix("3, 1, 0; -1, 0, 2")

In [25]:
print('A\n',A)
print('\nB\n',B)

A
 [[ 1 -5]
 [ 2  2]
 [ 0  3]]

B
 [[ 3  1  0]
 [-1  0  2]]


In [26]:
np.dot(A, B)

matrix([[  8,   1, -10],
        [  4,   2,   4],
        [ -3,   0,   6]])

In [27]:
np.dot(B, A)

matrix([[  5, -13],
        [ -1,  11]])

In [28]:
a=np.array([1,1])
b=np.array([2,-1])
c=np.array([1,2])

A=np.array([a,b,c]).T
print(A,'\n')

np.dot(A.T, A)

[[ 1  2  1]
 [ 1 -1  2]] 



array([[2, 1, 3],
       [1, 5, 0],
       [3, 0, 5]])

### добавить строку матрицы

In [29]:
A=np.zeros((3,3))
newrow = [1, 2, 3]
A = np.vstack([A, newrow])
A

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 2., 3.]])

добавить колонку матрицы

In [30]:
import numpy as np
N = 3
A = np.eye(N)

np.c_[ A, np.ones(N) ]              # add a column
# array([[ 1.,  0.,  0.,  1.],
    #    [ 0.,  1.,  0.,  1.],
    #    [ 0.,  0.,  1.,  1.]])

np.c_[ np.ones(N), A, np.ones(N) ]  # or two
# array([[ 1.,  1.,  0.,  0.,  1.],
    #    [ 1.,  0.,  1.,  0.,  1.],
    #    [ 1.,  0.,  0.,  1.,  1.]])

np.r_[ A, [A[1]] ]              # add a row
# array([[ 1.,  0.,  0.],
    #    [ 0.,  1.,  0.],
    #    [ 0.,  0.,  1.],
    #    [ 0.,  1.,  0.]])
# not np.r_[ A, A[1] ]

np.r_[ A[0], 1, 2, 3, A[1] ]    # mix vecs and scalars
#   array([ 1.,  0.,  0.,  1.,  2.,  3.,  0.,  1.,  0.])

np.r_[ A[0], [1, 2, 3], A[1] ]  # lists
#   array([ 1.,  0.,  0.,  1.,  2.,  3.,  0.,  1.,  0.])

np.r_[ A[0], (1, 2, 3), A[1] ]  # tuples
#   array([ 1.,  0.,  0.,  1.,  2.,  3.,  0.,  1.,  0.])

np.r_[ A[0], 1:4, A[1] ]        # same, 1:4 == arange(1,4) == 1,2,3
#   array([ 1.,  0.,  0.,  1.,  2.,  3.,  0.,  1.,  0.])

array([1., 0., 0., 1., 2., 3., 0., 1., 0.])

### Задание 7.1
Даны матрица  и вектор 

* A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
* x = np.array([1,2,3,4,5])
Найдите произведение матрицы A и вектора x в том порядке, в котором их можно умножить.

В качестве ответа запишите координаты получившегося вектора через запятую, без пробелов. Пример ввода ответа: 1,1.

In [31]:
A = np.array([[5,-1,3,1,2], [-2,8,5,-1,1]])
x = np.array([1,2,3,4,5])
A@x

array([26, 30])

### Задание 7.2
Даны две матрицы:

* A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
* B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
Найдите произведение матриц A и B в том порядке, в котором их можно умножить.

В качестве ответа через запятую, без пробелов запишите элемент чётвертого столбца первой строки.

In [32]:
A = np.array([[1,9,8,5], [3,6,3,2], [3,3,3,3], [0,2,5,9], [4,4,1,2]])
B = np.array([[1,-1,0,1,1], [-2,0,2,-1,1]])
(B@A)[0,3]

14

### Задание 7.3

Дана система векторов:

* x = np.array([1,2,1,0,4])
* y = np.array([2,1,-1,1,0])
* z = np.array([-1,1,-1,0,0])
Составьте матрицу A, расположив векторы x, y, z в строках. Найдите матрицу Грама G (матрицу скалярных произведений столбцов матрицы A) системы векторов x, y, z.

Чему равна полученная матрица Грама ?

In [71]:
x = np.array([1,2,1,0,4])
y = np.array([2,1,-1,1,0])
z = np.array([-1,1,-1,0,0])

A=np.array([x,y,z]).T

# матрица Грама ортонормированной системы векторов
# x_norm=x/np.linalg.norm(x)
# y_norm=y/np.linalg.norm(y)
# z_norm=z/np.linalg.norm(z)
# A_norm=np.array([x_norm,y_norm,z_norm])
# print (A_norm, type(A_norm))

A@A.T

array([[ 6,  3,  0,  2,  4],
       [ 3,  6,  0,  1,  8],
       [ 0,  0,  3, -1,  4],
       [ 2,  1, -1,  1,  0],
       [ 4,  8,  4,  0, 16]])

In [34]:
# содержится информация по количеству услуг, оказанных каждым стилистом за апрель
Count_DF = pd.DataFrame({
    'Женские стрижки': [10, 2, 12, 4, 6, 10, 22, 7], 
    'Мужские стрижки': [5, 21, 12, 8, 25, 3, 1, 0], 
    'Окрашивания':[12, 3, 0, 18, 27, 2, 4, 31],
    'Укладка':[15, 25, 30, 14, 25, 17, 25, 31],
    'Уход':[10, 6, 4, 5, 18, 12, 20, 28]
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)
# содержится информация по стоимости услуг у каждого стилиста в тысячах рублей
Price_DF = pd.DataFrame({
    'Женские стрижки': [2, 1.8, 2, 1.8, 2.5, 5, 1.1, 4.5], 
    'Мужские стрижки': [1.5, 2.5, 2, 1.2, 3.5, 5, 1, 4], 
    'Окрашивания':[1, 1, 0, 2.8, 2, 3, 1.5, 2.5],
    'Укладка':[0.8, 1, 0.5, 0.8, 1, 2, 0.5, 1],
    'Уход':[1, 1, 2, 2, 1.5, 2.5, 1.7, 2] 
    }, 
    index=['Аня', 'Борис', 'Вика', 'Галя', 'Дима', 'Егор', 'Женя','Юра']
)

In [35]:
display(Count_DF.head(1))
display(Price_DF.head(1))

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня               10                5           12       15    10

Женские стрижки  Мужские стрижки  Окрашивания  Укладка  Уход
Аня              2.0              1.5          1.0      0.8   1.0

### Задание 7.4

Найдите вектор дохода салона по стилистам, если за каждую услугу стилисты платят салону определённую «комиссию».

Вектор комиссий: com = np.array([0.2, 0.2, 0.3, 0.1, 0.1]).

Выберите координаты вектора прибыли салона:

In [36]:
com = np.array([0.2, 0.2, 0.3, 0.1, 0.1])
Count_ar=Count_DF.values
Price_ar=Price_DF.values
Co_Pr_ar=Count_ar*Price_ar
print(Co_Pr_ar@com)

[11.3  15.22 11.9  20.6  41.9  21.2  11.49 38.25]


### Задание 7.5

Найдите вектор дохода стилистов.

Выберите координаты полученного вектора:

In [37]:
print(Co_Pr_ar@(1-com))

[ 50.2   74.88  59.1   67.8  166.6  113.8   66.21 157.75]


In [38]:
A = np.matrix('1,2,3; 4,5,6; 7, 8, 10')
A

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8, 10]])

In [39]:
np.linalg.inv(A)

matrix([[-0.66666667, -1.33333333,  1.        ],
        [-0.66666667,  3.66666667, -2.        ],
        [ 1.        , -2.        ,  1.        ]])

### Определитель

In [40]:
import numpy as np
A = np.matrix ("1, 2, 3; 4, 5, 6 ; 7, 8, 10")
print(np.linalg.det(A))
# -3.0000000000009

-2.9999999999999982


In [41]:
A=np.array([[1,2],[1,1]])
B=np.array([[5,-2],[-1,4]])
print(np.linalg.det(A))
print(np.linalg.det(B))
print(np.linalg.det(A+B))

-1.0
17.999999999999996
29.99999999999999


In [42]:
A=np.array([[2,0,0],[0,1,0],[0,0,4]])
B=np.linalg.inv(A)
print(A)
print(np.linalg.det(A))
print(B)
print(np.linalg.det(B))

[[2 0 0]
 [0 1 0]
 [0 0 4]]
7.999999999999998
[[0.5  0.   0.  ]
 [0.   1.   0.  ]
 [0.   0.   0.25]]
0.12500000000000003


In [43]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,9,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 2

2


In [44]:
v1 = np.array([1,2,3,1])
v2 = np.array([4,5,6,1])
v3 = np.array([7,8,10,1])
A = np.array([v1, v2, v3]).T
print(np.linalg.matrix_rank(A))
# 3

3


In [56]:
A=np.eye(3)
A

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Задание 10.1
Дана матрица :

* A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
Найдите матрицу, обратную матрице .

В качестве ответа запишите элемент из первого столбца второй строки, округлив его до трёх знаков после точки-разделителя.

In [59]:
A = np.array([[8, 6, 11], [7, 5, 9],[6, 10, 6]])
print('A\n',A)
# проверка ранга матрици
print('rk(A):\n',np.linalg.matrix_rank(A))
# обратная матрица - все ок
A_inv=np.linalg.inv(A)
print('A inversed:\n',A_inv)

print('Ответ: ',round(A_inv[1,0],3))

A
 [[ 8  6 11]
 [ 7  5  9]
 [ 6 10  6]]
rk(A):
 3
A inversed:
 [[-1.875    2.3125  -0.03125]
 [ 0.375   -0.5625   0.15625]
 [ 1.25    -1.375   -0.0625 ]]
Ответ:  0.375


In [60]:
v1 = np.array([9, 10, 7, 7, 9])
v2 = np.array([2, 0, 5, 1, 4])
v3 = np.array([4, 0, 0, 4, 1])
v4 = np.array([3, -4, 3, -1, -4])

### Задание 10.2
Найдите ранг системы векторов v1, v2, v3, v4. Для этого создайте матрицу системы векторов. Векторы в матрице расположите в столбцы.

In [66]:
A=np.array([v1,v2,v3,v4]).T
print('A\n',A)
# проверка ранга матрици
print('rk(A):\n',np.linalg.matrix_rank(A))
# Ранг матрицы , составленной из векторов v1, v2, v3, v4 равен 4, что равно количеству векторов в системе.
# Это значит, что система векторов является линейно независимой.

A
 [[ 9  2  4  3]
 [10  0  0 -4]
 [ 7  5  0  3]
 [ 7  1  4 -1]
 [ 9  4  1 -4]]
rk(A):
 4


### Задание 10.4
Найдите матрицу Грама системы векторов v1, v2, v3, v4: G=A.T A. В качестве ответа запишите элемент из четвёртого столбца первой строки.

In [67]:
# матрицы Грама линейно независимой системы векторов
G=A.T@A
print('Матрица Грама:\n',G)
print('Ответ: ',G[0,3])

Матрица Грама:
 [[360  96  73 -35]
 [ 96  46  16   4]
 [ 73  16  33   4]
 [-35   4   4  51]]
Ответ:  -35


### Задание 10.5
Найдите определитель матрицы Грама G системы v1, v2, v3, v4. Ответ округлите до целого числа.

In [69]:
print('Определитель матрицы Грама:\n',round(np.linalg.det(G)))
# Определитель матрицы G отличен от нуля, значит матрица не вырождена.

Определитель матрицы Грама:
 3716648


### Задание 10.7
Найдите обратную матрицу к матрице Грама G системы v1, v2, v3, v4. В качестве ответа запишите элемент из первого столбца третьей строки, округлив его до трёх знаков после точки-разделителя.

In [70]:
G_inv=np.linalg.inv(G)
print('Обратная к матрице Грама:\n',G_inv)
print('Ответ: ',round(G_inv[2,0],3))

Обратная к матрице Грама:
 [[ 0.01711488 -0.02798543 -0.02623063  0.01599775]
 [-0.02798543  0.071967    0.03031441 -0.02722776]
 [-0.02623063  0.03031441  0.07683106 -0.02640498]
 [ 0.01599775 -0.02722776 -0.02640498  0.03479318]]
Ответ:  -0.026
