In [6]:
import numpy as np

In [7]:
# произведение матриц
A=np.random.randint(5, 12, (3,3))
B=np.random.randint(-2, 4, (3,3))

In [8]:
A

array([[11,  6,  6],
       [ 6, 11,  7],
       [ 9, 10,  9]])

In [9]:
B

array([[-1,  1,  1],
       [ 2,  1, -2],
       [-1,  1, -2]])

In [10]:
# Поэлементное умножение
A*B

array([[-11,   6,   6],
       [ 12,  11, -14],
       [ -9,  10, -18]])

In [11]:
# тип np.matrix
A_m=np.matrix(A)
B_m=np.matrix(B)
print(A_m*B_m)

[[ -5  23 -13]
 [  9  24 -30]
 [  2  28 -29]]


In [12]:
# Матричное умножение
np.dot(A,B)

array([[ -5,  23, -13],
       [  9,  24, -30],
       [  2,  28, -29]])

In [13]:
# Матричное умножение
A@B

array([[ -5,  23, -13],
       [  9,  24, -30],
       [  2,  28, -29]])

In [14]:
# Порядок умножения AB != BA
B@A

array([[  4,  15,  10],
       [ 10,   3,   1],
       [-23, -15, -17]])

In [15]:
# Умножение прямоугольных матриц возможно не в любом порядке
A=np.random.randint(5, 12, (3,5))
B=np.random.randint(-2, 4, (5,2))
print('A:\n',A)
print('B:\n',B)

A:
 [[ 8 10  6  8  5]
 [ 9 10  9  5  5]
 [ 9  7  6  9  6]]
B:
 [[ 3  2]
 [ 3  0]
 [ 2  0]
 [ 1  3]
 [ 3 -1]]


In [16]:
# Умножение прямоугольных матриц возможно не в любом порядке
A@B

array([[89, 35],
       [95, 28],
       [87, 39]])

In [17]:
# Умножение прямоугольных матриц возможно не в любом порядке
B@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [18]:
# размер произведения матриц
print('shape of A:', np.shape(A))
print('shape of B:', np.shape(B))
print('shape of AB:', np.shape(A@B))

shape of A: (3, 5)
shape of B: (5, 2)
shape of AB: (3, 2)


In [19]:
# умножение на специальные матрицы
A=np.random.randint(-4, 4, (4,4))
D=np.diag([1,2,0,-1])
print('A:\n',A)
print('D:\n',D)
print('AD:\n',A@D)
print('DA:\n',D@A)

A:
 [[-4  0 -4 -1]
 [-2  0 -1  0]
 [ 0  2  3 -2]
 [ 0  3 -2  0]]
D:
 [[ 1  0  0  0]
 [ 0  2  0  0]
 [ 0  0  0  0]
 [ 0  0  0 -1]]
AD:
 [[-4  0  0  1]
 [-2  0  0  0]
 [ 0  4  0  2]
 [ 0  6  0  0]]
DA:
 [[-4  0 -4 -1]
 [-4  0 -2  0]
 [ 0  0  0  0]
 [ 0 -3  2  0]]


In [20]:
# умножение на одномерный массив numpy
A=np.array([[1,0,1],[1,1,1]])
b=np.array([-3,4,5])
A@b

array([2, 6])

In [21]:
b@A

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [22]:
# матрица Грама ортогональной системы векторов
x=np.array([1,1,1])
y=np.array([1,0,-1])
z=np.array([-1,2,-1])
A=np.array([x,y,z])
print (A, type(A))

[[ 1  1  1]
 [ 1  0 -1]
 [-1  2 -1]] <class 'numpy.ndarray'>


In [23]:
# матрица Грама ортогональной системы векторов
A@A.T

array([[3, 0, 0],
       [0, 2, 0],
       [0, 0, 6]])

In [24]:
# матрица Грама ортонормированной системы векторов
x_norm=x/np.linalg.norm(x)
y_norm=y/np.linalg.norm(y)
z_norm=z/np.linalg.norm(z)
A_norm=np.array([x_norm,y_norm,z_norm])
print (A_norm, type(A_norm))

[[ 0.57735027  0.57735027  0.57735027]
 [ 0.70710678  0.         -0.70710678]
 [-0.40824829  0.81649658 -0.40824829]] <class 'numpy.ndarray'>


In [25]:
# матрица Грама ортонормированной системы векторов
A_norm@A_norm.T

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
# ортонормированные системы рулят! :)
np.round(A_norm@A_norm.T,1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])